### ISSUE TITLE
Getting local path of image or video

### ISSUE THREAD

**Issue by Ozzi48** [natysoz/expo-images-picker#11]
Now I can see in data array, that uri path is only remote (asset-library on ios), but how to get full local path?

**Comment by natysoz** [comment]
can u send here the Data array response your getting from the plugin ?

**Comment by Ozzi48** [comment]
Array [
  Object {
    "creationTime": 1615280192000,
    "duration": 0,
    "filename": "IMG_6925.PNG",
    "height": 1334,
    "id": "7A70C176-78BC-43FA-B6D2-9032934306E0/L0/001",
    "mediaSubtypes": Array [
      "screenshot",
    ],
    "mediaType": "photo",
    "modificationTime": 1615351413960,
    "uri": "assets-library://asset/asset.PNG?id=7A70C176-78BC-43FA-B6D2-9032934306E0&ext=PNG",
    "width": 750,
  },
  Object {
    "creationTime": 1615369270000,
    "duration": 0,
    "filename": "IMG_6929.PNG",
    "height": 1334,
    "id": "B5166E29-1E56-4630-8A0D-A71A8DCA9CF9/L0/001",
    "mediaSubtypes": Array [
      "screenshot",
    ],
    "mediaType": "photo",
    "modificationTime": 1615369270698,
    "uri": "assets-library://asset/asset.PNG?id=B5166E29-1E56-4630-8A0D-A71A8DCA9CF9&ext=PNG",
    "width": 750,
  },
]

Where the uri value is it possible to have "file://" local path? Now it is "assets-library://" and for example I cant send videos to firebase.

**Comment by natysoz** [comment]
i see this is a mediaSubtypes object , i didnt think about it because im an android user , this
"mediaSubtypes" means that the photo get shot with multi images saved , i will search for a solution for this issue

generally for now it will work only with "image" or "video" type , this "mediaSubtypes"
are Set of photos that iphone auto generate , you can disable it but yet ...

i will probably gonna check if image type is "mediaSubtypes" and then select the first image from the "set" as the asset, 

OR

Ignore (dont let select this type of Roll images) 

will see

**Comment by natysoz** [comment]
@Ozzi48 can u share your package json ?

**Comment by Ozzi48** [comment]
No, like for images everything is okey. I can use "assets-library://" uri, because when I push image to firebase it's works, but when I push video with remote uri, it is writing me that it is wrong path. And I have checked in forums that video should have local full path, like "file://".

**Comment by Ozzi48** [comment]
If I use expo-image-picker I got his url from picked picture **"file:///var/mobile/Containers/Data/Application/4BDCCE81-65BF-4834-A435-777E6388F199/Library/Caches/ExponentExperienceData/%2540ozzi38%252FVisionogy/ImagePicker/D474BD06-B3F7-4863-BCC0-9356FFCEBD2A.png"** , but when I use this package I get the link like **"assets-library://asset/asset.JPG?id=8360229E-BBF6-4143-91E6-4BC486E793A5&ext=JPG"**
So, is it possible to get full path , like from first package?

**Comment by natysoz** [comment]
still try to understand why its happen , because im dont have real iphone device but oneplus 8 i cant really find why

will keep investigate this

**Comment by natysoz** [comment]
hi i checked it and only when using `manipulate` images actually created on other folder but you should be able to upload them too

can you try with this snack=> https://snack.expo.io/@natysoz/expo-images-picker-example

see what results ur getting ?

**Comment by natysoz** [comment]
any update?

**Comment by Galterius** [comment]
@natysoz, Hi im using your package and i have the same problem, on iOS, it returns an assets-library type. On Android it works flawlessly.
Object {
    "creationTime": 1622194410000,
    "duration": 0,
    "filename": "IMG_0027.PNG",
    "height": 2208,
    "id": "C3583236-E568-418C-BABB-8008525CD0E7/L0/001",
    "mediaSubtypes": Array [
      "screenshot",
    ],
    "mediaType": "photo",
    "modificationTime": 1623407367433,
    "uri": "assets-library://asset/asset.PNG?id=C3583236-E568-418C-BABB-8008525CD0E7&ext=PNG",
    "width": 1242,
  },
I tried to find something to convert it into a normal local file but i had not success
SOLVED: if you use the manipulate option it will convert the file properly :D, this library saved my nerves. Thank you so much

**Comment by natysoz** [comment]
adding on the next version .

**Comment by natysoz** [comment]
added in new v2.0.0
