### ISSUE TITLE
Upload Images

### ISSUE THREAD

**Issue by KiltzX** [natysoz/expo-images-picker#14]
Hi, first, Thank you for this framework, its so helpful

i need to upload selected images, have one method to do this ?

**Comment by natemartins** [comment]
One method is to upload to backend server or to a 3rd party file hosting system like Cloudinary

**Comment by natysoz** [comment]
you can use your backend to generate PRE SIGNED URL , 
send this back to front end , and use it to POST images to this PRE SIGNED URL

in this way you go from

Upload from Client > server > server upload to Cloudinary > server return urls to client

to

Client ask Url from server > server return urls (take some 100-200ms ? ) > client upload directly to cloudinary

Good luck , this is not an issue , your welcome to join my discord channel i will give support and ideas there 

https://discord.gg/6XZ7Aqd2yK

**Comment by KiltzX** [comment]
Thank you guys, this resolve my problem
i send file path in my request using loopback 3 storage component and my photo upload with success, thank you
