### ISSUE TITLE
 Different styles for the button to go back and continue

### ISSUE THREAD

**Issue by KiltzX** [natysoz/expo-images-picker#16]
I want to set different style for this buttons, only color
Is possible ?

**Comment by natysoz** [comment]
you can send any valid style object to them 

 defaultTopNavigator: {
            .....
            buttonStyle: validViewStyleObject,
            textStyle: validTextStyleObject,
        },

**Comment by KiltzX** [comment]
i made one fork from this project, and modified params and view response to get
But, Thank you for help

Nice framework :) its so helpful

**Comment by natysoz** [comment]
sure thing :) thx
