### ISSUE TITLE
Android 7.1.1 ( Old phone ) blank screen

### ISSUE THREAD

**Issue by ioness** [natysoz/expo-images-picker#17]
This has been tested on a new expo project without anything else

```
"expo": "^40.0.0"
"expo-images-picker": "^1.3.0"
"expo-permissions": "~10.0.0"
```

### Devices I have personally tested today:

** DO WORK: **

iOS 12
iOS 14
Android 9

** DO NOT WORK: **

Android 7

### Last but not least

Thanks a lot for this lib

**Comment by natysoz** [comment]
Try with this snack => https://snack.expo.io/@natysoz/expo-images-picker-example

**Comment by natysoz** [comment]
Do you want to create DEVICES.MD and update with PRS each time u test new devices ?

if so , lets do that :)

**Comment by ioness** [comment]
> Try with this snack => https://snack.expo.io/@natysoz/expo-images-picker-example

That snack do work on Android 7

Will check everything and update my code

**Comment by ioness** [comment]
> Do you want to create DEVICES.MD and update with PRS each time u test new devices ?
> 
> if so , lets do that :)

I have to check why is it that it did not work on Android 7 last time, my fear is that I make mistakes and this DEVICES.MD just creates confusion

Sorry for the delay answering
