### ISSUE TITLE
Android 10.0 and 11.0 app gets crashed.

### ISSUE THREAD

**Issue by sehwagjain** [natysoz/expo-images-picker#18]
I have integrated this into my app. 
Works well for iOS and android versions <= 9.0

But it doesn't work version >=10.0.
As soon as we open gallery app gets crashed.

**Comment by natysoz** [comment]
can you share your package json ?

also , can you try to delete all images related to telegram folder and videos and try again ?

**Comment by sehwagjain** [comment]
Package.json 

{
  "main": "node_modules/expo/AppEntry.js",
  "scripts": {
    "start": "expo start",
    "android": "expo start --android",
    "ios": "expo start --ios",
    "web": "expo start --web",
    "eject": "expo eject"
  },
  "dependencies": {
    "@expo-google-fonts/abel": "^0.1.0",
    "@expo-google-fonts/bad-script": "^0.1.0",
    "@expo-google-fonts/courier-prime": "^0.1.0",
    "@expo-google-fonts/inconsolata": "^0.1.0",
    "@expo-google-fonts/inter": "^0.1.0",
    "@expo-google-fonts/nunito": "^0.1.0",
    "@expo-google-fonts/raleway": "^0.1.0",
    "@expo-google-fonts/roboto-mono": "^0.1.0",
    "@expo-google-fonts/source-code-pro": "^0.1.0",
    "@expo-google-fonts/space-mono": "^0.1.0",
    "@expo/vector-icons": "^10.2.0",
    "@mdi/font": "^5.5.55",
    "@mdi/js": "^5.5.55",
    "@mdi/react": "^1.4.0",
    "@react-native-community/masked-view": "^0.1.10",
    "@react-native-community/slider": "^3.0.3",
    "@react-native-picker/picker": "^1.9.10",
    "@react-navigation/native": "^5.8.10",
    "aws-sdk": "^2.778.0",
    "axios": "^0.19.2",
    "base64-arraybuffer": "^0.2.0",
    "buffer": "^5.6.1",
    "crypto-random-string": "^3.3.0",
    "expo": "^38.0.10",
    "expo-apple-authentication": "~2.2.1",
    "expo-av": "~8.2.1",
    "expo-blur": "~8.1.2",
    "expo-camera": "~8.3.1",
    "expo-facebook": "^9.0.0",
    "expo-file-system": "~9.0.1",
    "expo-font": "~8.2.1",
    "expo-gl": "~8.3.1",
    "expo-google-app-auth": "^8.1.3",
    "expo-image-manipulator": "~8.2.1",
    "expo-image-picker": "~8.3.0",
    "expo-images-picker": "^1.0.6",
    "expo-linear-gradient": "~8.2.1",
    "expo-linking": "^1.0.3",
    "expo-media-library": "~8.2.1",
    "expo-permissions": "~9.0.1",
    "expo-pixi": "^1.2.0",
    "expo-status-bar": "^1.0.2",
    "expo-web-browser": "~8.3.1",
    "form-data": "^3.0.0",
    "getstream": "^6.2.1",
    "gl-react": "^4.0.1",
    "gl-react-expo": "^4.0.1",
    "gl-react-image": "^3.1.1",
    "gl-react-native": "^4.0.1",
    "moment": "^2.29.1",
    "moment-timezone": "^0.5.31",
    "native-base": "^2.13.12",
    "react": "~16.11.0",
    "react-dom": "~16.11.0",
    "react-moment": "^1.0.0",
    "react-native": "https://github.com/expo/react-native/archive/sdk-38.0.1.tar.gz",
    "react-native-animated-pagination-dot": "^0.1.8",
    "react-native-aws3": "0.0.9",
    "react-native-bottom-menu": "^0.1.8",
    "react-native-elements": "^2.2.1",
    "react-native-flash-message": "^0.1.18",
    "react-native-fs": "^2.16.6",
    "react-native-gesture-handler": "~1.6.0",
    "react-native-image-filter": "^1.0.3",
    "react-native-image-picker": "^2.3.4",
    "react-native-keyboard-aware-scroll-view": "^0.9.2",
    "react-native-material-dropdown": "^0.11.1",
    "react-native-paper": "^4.7.2",
    "react-native-picker-select": "8.0.0",
    "react-native-popup-menu": "^0.15.9",
    "react-native-radio-button-group": "^1.0.3",
    "react-native-reanimated": "~1.9.0",
    "react-native-redash": "^14.2.3",
    "react-native-safe-area-context": "~3.0.7",
    "react-native-screens": "~2.9.0",
    "react-native-shapes": "^0.1.0",
    "react-native-snap-carousel": "^4.0.0-beta.5",
    "react-native-swipe-gestures": "^1.0.5",
    "react-native-syntax-highlighter": "^2.1.0",
    "react-native-vector-icons": "^7.0.0",
    "react-native-video-processing": "^1.20.0",
    "react-native-view-shot": "3.1.2",
    "react-native-web": "~0.11.7",
    "react-navigation": "^4.4.0",
    "react-navigation-stack": "^2.8.2",
    "react-navigation-tabs": "^2.9.0",
    "react-syntax-highlighter": "^15.2.1",
    "socket.io-client": "^3.0.4"
  },
  "devDependencies": {
    "@babel/core": "^7.8.6",
    "babel-preset-expo": "~8.1.0"
  },
  "private": true
}

**Comment by sehwagjain** [comment]
And how will I handle this telegram folder and videos? 
Any user can do that?

**Comment by sehwagjain** [comment]
Any update @natysoz  ??? 
I want to launch app asap. please reply?

**Comment by natysoz** [comment]
can u use this snack => https://snack.expo.io/@natysoz/expo-images-picker-example

open it on your device , and tell me what are the results ?

**Comment by natemartins** [comment]
I'm experiencing same issue especially when I upgraded the expo sdk to 41 and this package to ^1.3.2. The app crashes when I tap on a button to trigger the image gallery view.

Below is the error printed out in my console:

```
Error: Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: object.

Check the render method of `VirtualizedList`.

This error is located at:
    in RCTView (at View.js:34)
    in View (at ScrollView.js:1124)
    in RCTScrollView (at ScrollView.js:1260)
    in ScrollView (at ScrollView.js:1286)
    in ScrollView (at VirtualizedList.js:1329)
    in VirtualizedList (at FlatList.js:624)
    in FlatList (at AssetsSelectorList.tsx:105)
    in AssetsSelectorList (at AssetsSelector.tsx:262)
    in RCTView (at View.js:34)
    in View (created by Context.Consumer)
    in StyledNativeComponent (created by Styled(View))
    in Styled(View) (at AssetsSelector.tsx:261)
    in RCTView (at View.js:34)
    in View (created by Context.Consumer)
    in StyledNativeComponent (created by Styled(View))
    in Styled(View) (at AssetsSelector.tsx:238)
    in AssetsSelector (at GalleryViewScreen.js:28)
    in RCTView (at View.js:34)
    in View (at GalleryViewScreen.js:27)
    in RCTView (at View.js:34)
    in View (at SafeAreaView.js:41)
    in ForwardRef(SafeAreaView) (at Screen.js:9)
    in Screen (at GalleryViewScreen.js:26)
    in GalleryViewScreen (at SceneView.tsx:122)
    in StaticContainer
    in StaticContainer (at SceneView.tsx:115)
```

Below is a screenshot of the error shown on my device:

![20210603_072558](https://user-images.githubusercontent.com/49047480/120598199-e3dea300-c43d-11eb-8d25-759d0b82cbbb.jpg)

I commented out the AssetsSelector in my component rendering the images and my apps work fine. So, the issue is most likely coming from the AssetsSelector component.

Please, this is delaying me from publishing the update to my app. If you can expedite the solution, I'll really appreciate

**Comment by natysoz** [comment]
please update to 1.4.0 and try again

**Comment by natemartins** [comment]
Alright. Thanks man. I'm not currently with my PC. I will update this comment when I've updated the package to notify you of the outcome.

**Comment by natemartins** [comment]
> Alright. Thanks man. I'm not currently with my PC. I will update this comment when I've updated the package to notify you of the outcome.

Yep! Issue resolved. My app on the way to the stores.

**Comment by Marvin-Bai** [comment]
It works fine on my OnePlus 6t (Android 10). I haven't test Android 11 devices. 
Thanks for creating such great library.
One suggestion: it would be good that user could chose images from different albums. Like expo-image-picker, but it cannot select multiple photos :(
