### ISSUE TITLE
Custom TopNavigator Selected Items Length

### ISSUE THREAD

**Issue by ArcRanges** [natysoz/expo-images-picker#2]
Hi,

I would like to understand where 'translator' function is imported from or how to implement this properly.

```
 <AssetsSelector
  options={{
      ...otherProps,
      CustomTopNavigator: {
          Component: CustomNavImageSelection,
          props: {
              backFunction: true,
     -->      text: translator(T.PICK_IMAGES), <----
              doneFunction: (data: Asset[]) => onDone(data),
          },
      }
  }}
/>
```

Thank you for your help.

**Comment by natysoz** [comment]
hi ArcRanges , 

This is just my implementation for i18 , you can use any string you want for this variable ,
or , any function that will return string in the end.

My CustomNavigator for the Image selection is expecting to get text prop, 

You send with props:{}

the custom props u want to send to your CustomNavImageSelection or whatever dynamic component you have.

you can also not having custom top nav and not sending props at all :) ,

**Comment by ArcRanges** [comment]
I see,

How can I still show **Selected n items** on top bar?

I would like to edit the Default Top Bar itself but given the structure of the code, I think it would be a bit challenging.

Would you be able to add a `style` prop for the `DefaultTopNavigator` so I can override the styling of the:
- left button
- right button
- center text

If I have this, it would make everything easier.

Thank you so much.

**Comment by natysoz** [comment]
what style u are missing exactly ? you wanna change the size position and radius or the buttons ?

if you want i can upload a demo to show how to send custom nav that can also include the number of selected items

**Comment by ArcRanges** [comment]
Hi sorry for the late response,

I just need to manipulate the styling for the elements of the TopNavigator mentioned above.

Your demo would be helpful as well. Thank you.

**Comment by natysoz** [comment]
what exactly you want to edit can u send example of what you expect to have?

**Comment by ArcRanges** [comment]
![Screen Shot 2020-11-25 at 5 58 44 PM](https://user-images.githubusercontent.com/13533171/100299998-e968a700-2f49-11eb-988a-c9f8ff16e28f.png)

I just want to have the dynamic text that says **5 pictures selected.**

**Comment by natysoz** [comment]
![221](https://user-images.githubusercontent.com/16538415/101265774-c4e2ab00-3751-11eb-9cad-d3404e1d930c.JPG)
![aaa](https://user-images.githubusercontent.com/16538415/101265775-c57b4180-3751-11eb-94a9-7e4f001754dd.JPG)

i can add a style prop where you can send any valid ViewStyle object and it will overwrite , is that what you need ? i can add it quickly :)

**Comment by ArcRanges** [comment]
Yes. I would like that please. Thank you.

On Dec 5, 2020, at 1:30 PM, Natysoz <notifications@github.com> wrote:

﻿

[221]<https://user-images.githubusercontent.com/16538415/101265774-c4e2ab00-3751-11eb-9cad-d3404e1d930c.JPG>
[aaa]<https://user-images.githubusercontent.com/16538415/101265775-c57b4180-3751-11eb-94a9-7e4f001754dd.JPG>

i can add a style prop where you can send any valid ViewStyle object and it will overwrite , is that what you need ? i can add it quickly :)

**Comment by natysoz** [comment]
ok sorry for late response was too busy with my products , i will push new version tmr morning :)

**Comment by ArcRanges** [comment]
Thank you so much!

On Dec 5, 2020, at 1:46 PM, Natysoz <notifications@github.com> wrote:

﻿

ok sorry for late response was too busy with my products , i will push new version tmr morning :)

**Comment by natysoz** [comment]
I add a demo on expo snack so you can use this to understand the changes , 

at => https://snack.expo.io/@natysoz/expo-images-picker-example

few bugs was fixed , and you now can send style objects check Readme file 👍

**Comment by ArcRanges** [comment]
Thank you so much!

**Comment by jensonjohn001** [comment]
How to get selected items length in custom TopNavigator?
