### ISSUE TITLE
please npm publish new version

### ISSUE THREAD

**Issue by watanabeyu** [natysoz/expo-images-picker#25]
@natysoz 

This library's peerDependency of expo is yet `^40.0.0`, so this library can't use at expo v41.
Please `npm publish new version`

**Comment by natysoz** [comment]
on it

**Comment by watanabeyu** [comment]
now version is yet 1.3.2 (published a last month ago)
please update🙇‍♂️

![スクリーンショット 2021-05-18 11 38 55](https://user-images.githubusercontent.com/6455904/118582030-a3402200-b7cd-11eb-990d-181c9d7533ab.png)

**Comment by natysoz** [comment]
sorry as i just become a father :) i have 0 time in the last 1.5 weeks :) ill do that soon

**Comment by natemartins** [comment]
Congrats @natysoz . 

I think publishing a new npm version with support for expo SDK 41 will fix issue #18

**Comment by natysoz** [comment]
Done
