### ISSUE TITLE
Disable defaultTopNavigator 'Done' button if no item selected 

### ISSUE THREAD

**Issue by jensonjohn001** [natysoz/expo-images-picker#28]
Is there any way to get selected item length in the CustomTopNavigator component?
Can you pass `selected={selectedItems.length}`  props in `AssetSelector` `CustomTopNavigator.Component` so that I can manage done button based on length.
<img width="756" alt="Screen Shot 2021-06-09 at 9 04 00 PM" src="https://user-images.githubusercontent.com/35399770/121385750-02292f00-c967-11eb-8f56-9a86631168da.png">

Thank you.

**Comment by natysoz** [comment]
added in new v2.0.0
