### ISSUE TITLE
Upgrade to work with Expo 40

### ISSUE THREAD

**Issue by gayatrisss** [natysoz/expo-images-picker#3]
I'm seeing issues with using this library with the new expo 40.0.0 release. Specifically, some dependencies like the `expo-permissions` libraries have new syntax and changes that are not backwards compatible. 
eg: `Permissions.CAMERA_ROLL` -> `Permissions.MEDIA_LIBRARY`

https://github.com/natysoz/expo-images-picker/blob/fb2b37e8a6a161cfed5a7e0fe1d5efbcc6845d8e/src/AssetsSelector.tsx#L112

I'm upgrading my project to use expo 40 soon and would love to continue using this library.

**Comment by natysoz** [comment]
hi , ill probably change that to align with expo team , ill give it 1 week to see this guys dont change the api again and again :)

**Comment by adamblvck** [comment]
I'm stumbling on the same issue when using Expo SDK 40. Seems like `package.json` needs to be updated to latest expo-permissions, alongside changing CAMERA_ROLL to MEDIA_LIBRARY in lines 111-118 in `AssetsSelector.tsx`.

**Comment by natysoz** [comment]
yup , i notice that i just wonder if they going to update once again , they did update the api 3 times already :)

ETA for new version is tmr

**Comment by natysoz** [comment]
ok... release 1.2.0 checked and it works fine with expo 40 :) 

please open new issue if its not working for you with more tracing of the error 

https://www.npmjs.com/package/expo-images-picker

Thanks
