### ISSUE TITLE
Add mediaType to the result of resized image

### ISSUE THREAD

**Issue by jte0711** [natysoz/expo-images-picker#33]
hey guys, great work on the library. 

- **Proposed change:**
I think it would be great to add mediaTypes to the result of resizedImage

The reason is whenever we passed the widgetResize, it will only return `width`, `height`, `uri`, and possibly `base64` if user set it to true and all of the initial data from the asset such as `mediaType`, `filename`, etc are omitted from the response. It would be great to include some of them which still relevant to the data to the `resizedImage` response. 

I already have code ready, if you guys okay with it I can create a PR for it.

**Comment by natysoz** [comment]
sure create a pr and lets discuss it

**Comment by jte0711** [comment]
@natysoz great! I just created it, it's #34

**Comment by natysoz** [comment]
ok merging
