### ISSUE TITLE
Cant get the Uri as a valid uri prop for an Image

### ISSUE THREAD

**Issue by josemanuel151** [natysoz/expo-images-picker#35]
I try to render the picked images Uri but it are like invalid because displays nothing

**Comment by natysoz** [comment]
Can u share code for the component that render ?

**Comment by josemanuel151** [comment]
Here is bro: 
<FlatList
            ListEmptyComponent={<Text>Loading...</Text>} 
            data={filteredUri}
            renderItem={(item) => (
              <View>
                <Image source={item} style={{ widht: 100, height: 100 }} />
              </View>
            )}
          />

**Comment by josemanuel151** [comment]
I make this to get an array of only the uris:
 const onSuccess = (data: any) => {  
    console.log(data)      
    const filteredUri = data.filter(({ uri }) => uri).map(({ uri }) => uri);
    navigation.navigate('AddProductScreen', 
    {
      filteredUri: filteredUri,
    });
  };
And the I try to use them here:
<FlatList
            ListEmptyComponent={<Text>Loading...</Text>} 
            data={filteredUri}
            renderItem={(item) => (
              <View>
                <Image source={item} style={{ widht: 100, height: 100 }} />
              </View>
            )}
          />

**Comment by natysoz** [comment]
if you send data[0].uri to the <image> component it display the image ? if so you have issue with the filters your making

**Comment by josemanuel151** [comment]
I think that is something bad with my component

**Comment by josemanuel151** [comment]
I cant use assets-library uri on my image component, do you know how can I display it :(
