### ISSUE TITLE
Incompatibility with Expo 43

### ISSUE THREAD

**Issue by oliverwelter** [natysoz/expo-images-picker#38]
After upgrading to expo 43 the following error appears:
Unable to resolve module @unimodules/core 

expo-image-manipulator/build/ImageManipulator.js: @unimodules/core could not be found within the project or in these directories

Looking at the documentation of expo 43 upgrade it mentions that the original unimodules have been removed.

**Comment by monceeef** [comment]
Same here, will try to make a PR to address it.
@natysoz can you please upgrade to these version? 
 
`   "expo-image-manipulator": "^10.1.2",
    "expo-media-library": "^13.0.3",
`

**Comment by natysoz** [comment]
yhea ill do that tmr

**Comment by natysoz** [comment]
done , please reinstall and tell me if SDK 43 now works for you.

**Comment by natysoz** [comment]
please open new issue if this continue with latest version
