### ISSUE TITLE
Error with mediaLibrary

### ISSUE THREAD

**Issue by NyashaNziramasanga** [natysoz/expo-images-picker#4]
Ho do I resolve this issue, it started recently after the recent update which prevents any media from displaying.

![IMG_2996](https://user-images.githubusercontent.com/47994666/104334706-9de27a80-5542-11eb-8c39-e165f246bff7.PNG)

**Comment by natysoz** [comment]
hi do you update your expo SDK to version 40 ?

**Comment by NyashaNziramasanga** [comment]
Cheers the solution was to upgrade to Expo SDK 40
