### ISSUE TITLE
Add more flexibility for the style of the Screen and Widget

### ISSUE THREAD

**Issue by jte0711** [natysoz/expo-images-picker#40]
Hi, I think it would be great if we could let user to customise the component style a bit more (e.g `borderRadius`). Currently we limit them with a few styles such as `margin`, `bgcolor`, and `widgetWidth`.

I have a PR about adding `borderRadius` to the style. #39

**Comment by natysoz** [comment]
ok will merge after u fix conflicts

**Comment by natysoz** [comment]
we can send in style object and assign default one if none if u want to create a pr ur welcome

**Comment by jte0711** [comment]
@natysoz , yea sure. I can work on it when I'm free

**Comment by natysoz** [comment]
I remove the border u added because it was typed wrong and make issues with the build , 

Let's work together on adding an object of styling for the screen so we won't have to send border separate or later on border color or ....

**Comment by jte0711** [comment]
> I remove the border u added because it was typed wrong and make issues with the build ,

ok no problem. Do you mind sharing what was wrong with the type?

> Let's work together on adding an object of styling for the screen so we won't have to send border separate or later on border color or ....

Yea sure. how do you want it to look like? will it be part of the current `widgetStyles`?

**Comment by natysoz** [comment]
yhea i think , we can send in an object and just pass it on and spread it , like i did with th default navigator buttons

**Comment by bengold14** [comment]
Hi - just wanted to say thanks for the component, I would also love a way to add a border radius to the photos in the selection.  Let me know if you need help with the PR

**Comment by jte0711** [comment]
hi @natysoz, I opened a PR about customizing the screen style and the widget style, please check it here #43

**Comment by natysoz** [comment]
hi sorry for the delay ill look at this pr today

**Comment by jte0711** [comment]
> hi sorry for the delay ill look at this pr today

no problem, let me know if there's anything wrong with it

**Comment by EKOLX** [comment]
Hey guys, there is UI issue. Header navigation component goes offset to the left. I'm using same code from documentation.
<img width="356" alt="Screen Shot 2021-12-28 at 22 25 36" src="https://user-images.githubusercontent.com/24255958/147595825-59f25b44-f419-40e5-8d0c-1589252811f4.png">
