### ISSUE TITLE
Header navigation component goes offset to the left

### ISSUE THREAD

**Issue by EKOLX** [natysoz/expo-images-picker#46]
Hey guys, there is UI issue. Header navigation component goes offset to the left. I'm using same code from documentation.

<img width="338" alt="Screen Shot 2021-12-28 at 22 30 24" src="https://user-images.githubusercontent.com/24255958/147596168-7bf325cb-7fe3-43f5-a51c-674203f6a2b6.png">
<img width="423" alt="Screen Shot 2021-12-28 at 22 31 35" src="https://user-images.githubusercontent.com/24255958/147596248-d2c06f28-15e3-4667-b13d-d64535ef96fe.png">
<img width="347" alt="Screen Shot 2021-12-28 at 22 31 53" src="https://user-images.githubusercontent.com/24255958/147596268-f25b703b-cebf-475d-8b33-efba42cf5de6.png">

**Comment by EKOLX** [comment]
How get error message? I don't select any file, on pressing button on header I don't get any error either.

**Comment by natysoz** [comment]
can u share expo snack to reproduce ?
