### ISSUE TITLE
Old dependencies on expo packages crashes build for expo sdk 44

### ISSUE THREAD

**Issue by iaminarush** [natysoz/expo-images-picker#48]
EAS build failed on sdk 44, after some googling I think that the dependency on `expo-media-library 13.0.3` and `expo-image-manipulator 10.1.2` is causing the problem since they use a outdated version of `expo-modules-core`. Yarn why output: 

```
yarn why v1.22.17
[1/4] 🤔  Why do we have the module "expo-modules-core"...?
[2/4] 🚚  Initialising dependency graph...
[3/4] 🔍  Finding dependency...
[4/4] 🚡  Calculating file sizes...
=> Found "expo-modules-core@0.4.10"
info Has been hoisted to "expo-modules-core"
info Reasons this module exists
   - Hoisted from "expo-images-picker#expo-image-manipulator#expo-modules-core"
   - Hoisted from "expo-images-picker#expo-media-library#expo-modules-core"
info Disk size without dependencies: "1.57MB"
info Disk size with unique dependencies: "1.63MB"
info Disk size with transitive dependencies: "1.69MB"
info Number of shared dependencies: 4
=> Found "expo#expo-modules-core@0.6.4"
info This module exists because "expo" depends on it.
info Disk size without dependencies: "2.02MB"
info Disk size with unique dependencies: "2.08MB"
info Disk size with transitive dependencies: "2.14MB"
info Number of shared dependencies: 4
✨  Done in 0.92s.
```
According to [this](https://github.com/expo/expo/issues/15680#issuecomment-1002709123) the outdated libraries that depend on a older version of expo-modules-core seems to be making the build crash.

Good news is that you can bypass this by using yarn resolutions to set the expo libraries version, currently added this to my package.json and your library still works.
```
"resolutions": {
    "**/expo-media-library": "~14.0.0",
    "**/expo-image-manipulator": "~10.2.0"
  }
```

**Comment by natysoz** [comment]
im waiting for sdk 45 and >14.0.0 

there is a big issue for permissions that really stuck me from pushing with the plugin

**Comment by natysoz** [comment]
i help them find the issue and solve it but we wait for next release 
https://github.com/expo/expo/issues/15273#issuecomment-1022011792

**Comment by natysoz** [comment]
will update once sdk 45 is out
