### ISSUE TITLE
Option to manipulator selected images

### ISSUE THREAD

**Issue by NyashaNziramasanga** [natysoz/expo-images-picker#5]
Ability to **compress** or **resize** the selected images using the [expo imageManipulator](https://docs.expo.io/versions/latest/sdk/imagemanipulator/)

**Comment by natysoz** [comment]
will add in the next update :) both base64 support and resize

**Comment by natemartins** [comment]
> will add in the next update :) both base64 support and resize

When will this update be coming out? I seriously need the base64 support and the deadline for the project I'm working on has passed. Please, the earlier the better.

Another thing, the data returned from the images selected does not include an md5. Can you add that?

**Comment by natysoz** [comment]
hi later today we deploy new ver include resize , compress , and base64 options

**Comment by natysoz** [comment]
Done enjoy , if you got issues make sure to run expo r -c to clear expo caching .
