### ISSUE TITLE
Expo module dependencies should be devDependencies

### ISSUE THREAD

**Issue by brentvatne** [natysoz/expo-images-picker#50]
In order to make it easier to support multiple SDK versions with a single version of this package, it would be best to ask developers to install `expo-image-manipulator` and `expo-media-library` in the README by adding `expo install expo-image-manipulator expo-media-library` to the installation instructions. You can then just move these libraries to devDependencies in `package.json`.

**Comment by natysoz** [comment]
the big issue is that each time they update this packages they are doing breaking changes ... so i want to stay consistence with a version that works for 100% if u for example run SDK 43 today with this packages version it should work 

but you right , ill change that in the end.

**Comment by brentvatne** [comment]
@natysoz - generally the APIs from these libraries are pretty stable. that said, we need to expose a way for libraries like expo-images-picker to hook into `expo install` so we can ensure we install a compatible version of packages outside of Expo SDK too :)

**Comment by natysoz** [comment]
agree im still waiting for them to release sdk 45 :(

**Comment by natysoz** [comment]
the permission issues for managed workflow is crazy so many peoples cant use it correctly atm.

**Comment by brentvatne** [comment]
@natysoz - which permissions issue?

SDK 45 will be released at the end of April

**Comment by andrey-grach** [comment]
> @natysoz - which permissions issue?
> 
> SDK 45 will be released at the end of April

Hi! In Expo works fine, when I created standalone App on Android v. 8.0.0 still works fine but on new versions of Android error with permissions like this: https://github.com/natysoz/expo-images-picker/issues/44 and 
https://github.com/expo/expo/issues/15273 

On IOS I didn't notice any problems.

**Comment by natysoz** [comment]
iv update packages versions
it now should work on eas build , and on local (if u grant permission on first time)

ill finally fix the permissions issue when sdk 45 is out
