### ISSUE TITLE
Add possibility to filter images

### ISSUE THREAD

**Issue by The098** [natysoz/expo-images-picker#52]
Congratulations sir for this package, awesome. It will be great to be able to filter images by the date asc/desc, or size, or name etc to facilitate the research of images we cannot pick them per album.

Thank  you

Cheers

**Comment by natysoz** [comment]
im working on let users pick by album :) ill add this too thanks

**Comment by The098** [comment]
Thank for the reply, will the next version support expo go? Or it will
require custom native code...

**Comment by natysoz** [comment]
this package will work with expo managed workflow

**Comment by The098** [comment]
Thank you for your email, good luck, very excited to work with it
