### ISSUE TITLE
Is there any way to select galery albums ?

### ISSUE THREAD

**Issue by shop-fluencer** [natysoz/expo-images-picker#55]
title says

**Comment by natysoz** [comment]
wip feature in next month maybe ill finish and add it

**Comment by bengold14** [comment]
Hi @natysoz - just wanted to check and see if this is still wip? I am happy to help create this functionality if you would like me to take a look.

**Comment by isabellaskc** [comment]
Hi @natysoz - noticed that this tread is closed (as completed), how do i access this feature?
