### ISSUE TITLE
Returning ph:// uri on IOS

### ISSUE THREAD

**Issue by stefanleoussis** [natysoz/expo-images-picker#57]
Hi there, not really sure where to ask this but here it goes.

I am getting a ph:// prefixed uri returned on IOS when a video is selected, however I get the usual file:// prefix when it is selected on Android. This is only happening as of recently switching from the managed to bare workflow.

I am also not getting the .mov extension that is expected for  IOS.

Please let me know,
Thank you, All the best.

**Comment by Parth8733** [comment]
Hi there,
I am facing the same issue.

please let me know if there is any workaround or solution to this.

thank you.

**Comment by scottdj92** [comment]
You can enable `getImageMetadata` in the Settings prop to get `localUri` which has the `file://` prefix.
