### ISSUE TITLE
can not convert image file .heic

### ISSUE THREAD

**Issue by nanokoko89** [natysoz/expo-images-picker#64]
I upload jpg and png ok but .heic is not show
Here is localUri: file:///var/mobile/Media/DCIM/101APPLE/IMG_1971.HEIC

Anyone have this problem. Thanks you

**Comment by natysoz** [comment]
just rename to jpg before u upload should work fine

**Comment by nanokoko89** [comment]
It still does not work. 
I change .HEIC to .JPG but can not upload it, PNG upload ok but HEIC error:

expo%5CAppEntry.bundle?platform=ios&dev=true&hot=false:21070:21
callFunctionReturnFlushedQueue@[native code] LOG  HEIC
 LOG  HEIC LOG  ["file:///var/mobile/Media/DCIM/101APPLE/IMG_1973.JPG", "file:///var/mobile/Media/DCIM/101APPLE/IMG_1972.PNG", "file:///var/mobile/Media/DCIM/101APPLE/IMG_1971.JPG", "file:///var/mobile/Media/DCIM/101APPLE/IMG_1970.JPG"]
 LOG  HEIC
 LOG  HEIC
 LOG  ["file:///var/mobile/Media/DCIM/101APPLE/IMG_1973.JPG", "file:///var/mobile/Media/DCIM/101APPLE/IMG_1972.PNG", "file:///var/mobile/Media/DCIM/101APPLE/IMG_1971.JPG", "file:///var/mobile/Media/DCIM/101APPLE/IMG_1970.JPG"]
 LOG  {"isTrusted": false}
 LOG  {"isTrusted": false}
 WARN  Possible Unhandled Promise Rejection (id: 16):

**Comment by natysoz** [comment]
im not sure its related to the package

**Comment by drcodecamp** [comment]
did u find any solution?
