### ISSUE TITLE
[IOS] Images not showing(blank screen) 

### ISSUE THREAD

**Issue by Kladislav** [natysoz/expo-images-picker#7]

**Comment by natysoz** [comment]
can u share expo version ? and package json

**Comment by alekkyo** [comment]
I had a permission problem also. You can go check my pull request. https://github.com/natysoz/expo-images-picker/pull/8/files

**Comment by natysoz** [comment]
@Kladislav can u tell me what is your ios version , 
what iphone emulator ?
and what expo-images-picker version you try ?

i just test with my iphone and all working like a charm , wonder what we can do to improve that

**Comment by cardyy** [comment]
works fine for me, i can not express how greatful i am

**Comment by natysoz** [comment]
@Kladislav and @alekkyo did u update to latest versions and all is working ?

**Comment by natemartins** [comment]
I had same issue but after reinstalling my simulator. It works fine. Also works great in production. So, I think this issue should be closed

**Comment by Jeet1912** [comment]
I still face this issue. Selected images were only displayed for the first run. Subsequent runs just return a blank screen.

**Comment by jeet1912** [comment]
Blank screen for me. I could see the selected images during the first test only. After that, it's just a blank screen on my iphone.

**Comment by natysoz** [comment]
@Jeet1912 what ios version ?
Emulator ? Real device?

**Comment by jeet1912** [comment]
11 pro max, 14.0

**Comment by natysoz** [comment]
can you share your package json ?

**Comment by natysoz** [comment]
i just check on my wife iphone 12 pro max ios 14.0 all works correctly

**Comment by natysoz** [comment]
are you there? did u check with last expo snack on readme ?
